name: JustAFK
main: net.alexben.JustAFK.JustAFK
version: Alpha_2.1.0.2
description: A simple AFK plugin 
authors: [_Alex, aappleton3]
database: false
softdepend: [PlaceholderAPI, EssentialsX]
commands:
  afk:
    description: The basic command to toggle AFK status 
    usage: /afk [<reason>]
    aliases: [aafk, afkme]
  justafk:
    description: Gives some information about JustAFK 
    usage: /justafk
    aliases: [jafk]
  whosafk:
    description: Lists the AFK players 
    usage: /whosafk
    aliases: [wafk, whoafk, listafk]
  setafk:
    description: Set the AFK status of another player 
    usage: /setafk <player> [<reason>]
    aliases: [safk]
  afkhelp:
    description: Shows the help page
    usage: /afkhelp
    aliases: [hafk, helpafk, afkh]
  isafk:
    description: See if someone is AFK and get the reason if the player is 
    usage: /isafk <player>
    aliases: [iafk]
  afkconfig:
    description: The command to save and reload the config for JustAFK 
    usage: /afkconfig save|reload|{list <file>}|{get <file> <field>}|{set <file> <field> [sub-field] <value>}
    aliases: [cafk]
  afkkickall:
    description: The command to kick all AFK players 
    usage: /afkkickall [force]
    aliases: [kafk, afkickall]
  afkplayer:
    description: The command to manage player AFK settings 
    usage: /afkplayer [<player>] <setting> <value>
    aliases: [pafk, playerafk, afkp]
permissions:
  justafk.*:
    description: The root JustAFK permission
    default: op
    children:
      justafk.afk: true
      justafk.list: true
      justafk.isafk: true
      justafk.setafk: true
      justafk.kickall.force: true
      justafk.immune.*: true
      justafk.config.*: true
      justafk.player.*: true
  justafk.afk:
    description: The default permission for players to set their AFK status.
    default: op
  justafk.list:
    description: The permission to list AFK players. 
    default: op
  justafk.isafk:
    description: The permission to see if a player is AFK. 
    default: op
  justafk.setafk:
    description: The permission to set another player as AFK.
    default: op
  justafk.immune.*:
    description: Makes the player immune to automatic kicking and lightning.
    default: op
    children:
      justafk.immune.afk: true
      justafk.immune.kick: true
      justafk.immune.lightning: true
  justafk.immune.afk:
    description: Makes the player immune to being set to AFK after a set interval of time. 
    default: op
  justafk.immune.kick:
    description: Makes the player immune to being kicked. 
    default: op
  justafk.immune.lightning:
    description: Makes the player immune to lightning. 
    default: op
  justafk.kickall.force:
    description: Lets the player kick all AFK players 
    default: op
    children:
      justafk.kickall: true
  justafk.kickall:
    description: Lets the player kick all non-exempt AFK players 
    default: op
  justafk.config.*:
    description: The root config management permissions. 
    default: op
    children: 
      justafk.config.seemessages: true
      justafk.config.save: true
      justafk.config.reload: true
      justafk.config.set.*: true
  justafk.config.seemessages:
    description: Makes the player able to see config messages. 
    default: op
  justafk.config.save:
    description: Makes the player able to save the config. 
    default: op
  justafk.config.reload:
    description: Makes the player able to reload the config.
    default: op
  justafk.config.set.*:
    description: Set the config values 
    default: op
    children:
      justafk.config.set.config: true
      justafk.config.set.localisation: true
      justafk.config.set.players: true
      justafk.config.get: true
  justafk.config.set.config:
    description: Set the config values in the config file 
    default: op
  justafk.config.set.localisation:
    description: Set the config values in the localisation file 
    default: op
  justafk.config.set.players:
    description: Set the config values in the players file
    default: op
    children:
      justafk.player.afkexempt.others: true
      justafk.player.seehidden.others: true
      justafk.player.kickexempt.others: true
      justafk.player.lightningexempt.others: true
  justafk.config.get:
    description: Get the config values 
    default: op
  justafk.player.*:
    description: Set AFK player settings 
    default: op
    children:
      justafk.player.afkexempt.others: true
      justafk.player.seehidden.others: true
      justafk.player.kickexempt.others: true
      justafk.player.lightningexempt.others: true
  justafk.player.afkexempt.others: 
    description: Set whether players have exemption from being automatically set AFK or not 
    default: op
    children:
      justafk.player.afkexempt: true
  justafk.player.afkexempt:
    description: Set whether you have exemption from being automatically set AFK or not 
    default: op
  justafk.player.seehidden.others:
    description: Set whether players can see AFK hidden players or not 
    default: op
    children:
      justafk.player.seehidden: true
  justafk.player.seehidden:
    description: Set whether you can see AFK hidden players or not 
    default: op
  justafk.player.kickexempt.others:
    description: Set whether players are exempt from being kicked if they are AFK or not 
    default: op
    children:
      justafk.player.kickexempt: true
  justafk.player.kickexempt:
    description: Set whether you are exempt from being kicked if you are AFK or not 
    default: op
  justafk.player.lightningexempt.others:
    description: Set whether plyers are exempt from lightning when they go AFK or not 
    default: op
    children:
      justafk.player.lightningexempt: true
  justafk.player.lightningexempt:
    description: Set whether you are exempt from lightning when you go AFK or not 
    default: op
