tagmessages: true
colourchar: '&'
autokick: true
lightning: false
hideawayplayers: true
broadcastawaymsg: true
broadcastkickmessage: true
movementcheckfreq: 30 
kicktime: 60 
inactivetime: 90
kickwhileinvehicle: true
returnonlook: true
